image: node:18

stages:
  - install
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# INSTALA DEPENDÊNCIAS
install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

# TESTES
test:
  stage: test
  script:
    - npm run lint || true
  dependencies:
    - install

# BUILD
build:
  stage: build
  script:
    - npm run build
  dependencies:
    - install
  artifacts:
    paths:
      - .next/
    expire_in: 1 hour
  only:
    - main